### PR TITLE
Added ocaml

### PR DESCRIPTION
**Pull request by DavidTruby**
Added an ocaml solution. Performance roughly half of java on my machine.

### CODE REVIEW

**Comment by luke5542** [comment]
Your makefile echos "Running rust sieve".

Other than that, and the awkward installation of ocaml, just need to test the docker build and this should be good to merge.

**Comment by luke5542** [comment]
Actually, I just realized that the clean-failure we've had setup is also broken with this. I didn't have either dependency installed yet it didn't detect this and thus tried to build/run the ocaml anyway, which failed and stopped any other languages from running. This is likely an issue with the Makefile's EXECUTABLES list.

**Comment by DavidTruby** [comment]
The clean failure didn't work for me on the branch I cloned from you. I didn't have scala or D installed and it tried to build anyway so I don't think that breakage is to do with this commit, maybe it broke some time before?

**Comment by luke5542** [comment]
Hmm... okay then. I'll admit I didn't test every language's existence for the clean failure, but I know it was working on some of them, specifically the python sets, so I'll create a new issue for that.

That just leaves docker testing.

**Comment by georgevanburgh** [comment]
This failed the build with the following error:

```
make[1]: Entering directory `/root/src/sieve-of-eratosthenes/ocaml' opam install core
3458[ERROR] Please run 'opam init' first to initialize the state of OPAM. 'opam install core' failed.
3459make[1]: Leaving directory `/root/src/sieve-of-eratosthenes/ocaml'
3460make[1]: *** [sieve_ocaml.native] Error 66
3461make: *** [buildall] Error 2
```

**Pull request merged**
